"""initial table

Revision ID: 19a4f394a8a8
Revises: 
Create Date: 2024-02-20 17:52:40.370705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19a4f394a8a8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.VARCHAR(length=128), nullable=True),
    sa.Column('title', sa.VARCHAR(length=256), nullable=True),
    sa.Column('url', sa.VARCHAR(length=128), nullable=True),
    sa.Column('published_dt', sa.VARCHAR(length=128), nullable=True),
    sa.Column('meta_description', sa.VARCHAR(length=256), nullable=True),
    sa.Column('currency_curs', sa.FLOAT(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('tags', sa.VARCHAR(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article')
    # ### end Alembic commands ###
