"""Change published_dt column type to TIMESTAMP

Revision ID: b4f045c6dd40
Revises: initial
Create Date: 2024-05-27 21:39:49.390750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4f045c6dd40'
down_revision: Union[str, None] = 'initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article', 'published_dt', type_=sa.TIMESTAMP)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article', 'published_dt', type_=sa.DATETIME)
    # ### end Alembic commands ###
