"""renew models_db

Revision ID: d82e3abcf49c
Revises: 95ae2f780304
Create Date: 2024-05-21 15:42:39.400996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd82e3abcf49c'
down_revision: Union[str, None] = '95ae2f780304'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article', 'published_dt',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index('idx_published_dt', table_name='article')
    op.drop_column('article', 'article_id')
    op.drop_column('article', 'tags')
    op.drop_column('article', 'meta_description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('meta_description', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.add_column('article', sa.Column('tags', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.add_column('article', sa.Column('article_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.create_index('idx_published_dt', 'article', ['published_dt'], unique=False)
    op.alter_column('article', 'published_dt',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    # ### end Alembic commands ###
